#!/usr/bin/env python2
"""
Test script to ensure cron can kickoff Python scripts.
Also log the environment variables to a file (~/.log/cron.log), to
verify the shared cron environment variables are visible to Python.
"""
import os

HOME=os.path.expanduser('~')
LOGDIR=os.path.join(HOME, ".log")
LOGFILE=os.path.join(LOGDIR, 'cron.log')

# make log directory
try:
    os.makedirs(LOGDIR)
except OSError:
    # suppress stupid error if directory already exists
    pass

# Overwrite existing logfile
with open(LOGFILE, 'w') as f:
    f.write("------------------\n")
    f.write("Python view of env vars:\n")
    for k, v in os.environ.iteritems():
        f.write("{}: {}\n".format(k, v))

