#!/usr/bin/env python2
"""
Test script to ensure cron can kickoff Python scripts.
Also log the environment variables to a file (~/.log/cron.log), to
verify the shared cron environment variables are visible to Python.
"""
import json
import os
import sys


def logvars():
    """Log environment variables"""
    logdir = os.environ.get("LOGDIR")
    logfile = os.path.join(logdir, 'cron-env.json')

    # Overwrite existing logfile
    with open(logfile, 'w') as f:
        json.dump(dict(os.environ), f, indent=2)
        print "Wrote environment variables to: {}".format(logfile)


filename = sys.argv[0]
testvalue = os.environ.get("TESTVAR", "")
print "Filename: {}".format(filename)
print "TESTVAR: {}".format(testvalue)

logvars()
